In [ ]:
Reference : https://scikit-learn.org/stable/tutorial/basic/tutorial.html#machine-learning-the-problem-setting

Definitions : 

** Machine Learning** 

Defined as learning some properties of a data set and then testing those properties against another data set- evaluate an algorithm by splitting a data set into two : training and testing set.

A learning problem that considers a set of n samples of data and then tries to predict properties of unknown data. These learning problems fall into a few categories : 

- Supervised learning- the data comes with additional attributes that we want to predict 
    - Classification - samples belong to one or more classes and we want to learn from already labeled data how to predict the class of unlabeled data
    - Regression - if the desired output consists of one or more continous variables , then the task is called regression
- Unsupervised learning - in which the training data consists of a set of input vectors x without any corresponding target values

Loading the required datasets : 

In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [2]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

data is always a 2D array , shape ( n_samples, n_features),although the original data may have had a different shape. 

External datasets : loading
Here are some recommended ways to load standard columnar data into a format usable by scikit-learn:

pandas.io provides tools to read data from common formats including CSV, Excel, JSON and SQL. DataFrames may also be constructed from lists of tuples or dicts. Pandas handles heterogeneous data smoothly and provides tools for manipulation and conversion into a numeric array suitable for scikit-learn.

scipy.io specializes in binary formats often used in scientific computing context such as .mat and .arff

numpy/routines.io for standard loading of columnar data into numpy arrays

scikit-learn’s datasets.load_svmlight_file for the svmlight or libSVM sparse format

scikit-learn’s datasets.load_files for directories of text files where the name of each directory is the name of each category and each file inside of each directory corresponds to one sample from that category


Learning and predicting :

For the digits dataset , the task is to predict , given an image which it represents. Samples of each of the 10 possible classes on which we fit an estimator to be able to predict the classes to which unseen samples belong
In SCIKIT-LEARN , an estimator for classification is a python object that implements support vector classification.

In [8]:
from sklearn import svm
>>> clf = svm.SVC(gamma=0.001, C=100.0)

clf  is estimator instance fitted to the model- to learn from the model.
The learning is done by passing our training set to the fit method - using images from our dataset , leaving out the last image which we reserve for our predicting. The training set withe [:-1] will product a new array that contains all but the last iteam from digits.data

In [10]:
from sklearn import datasets
digits = datasets.load_digits()

from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(digits.data[:-1], digits.target[:-1])


SVC(C=100.0, gamma=0.001)

In [9]:
import numpy as np
clf.predict(digits.data[-1:])


array([8])